name: 'SwiftCICD'
description: 'Run SwiftCICD'
inputs:
  package-path:
    description: 'Path to the directory containing the Package.swift which defines your CICD executable target.'
    required: false
    default: '.github/workflows/cicd'
  github-token:
    description: 'Your GitHub token is needed in order to interact with the GitHub API on your behalf. (Use: github.token)'
    required: false
    default: ${{ github.token }}

runs:
  using: 'node16'
  main: 'dist/index.js'
